export let FORM_VERIFICAR_PTD = {
    //titulo_i18n: 'ptd.info_docente',
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Guardar',
    modelo: 'VerificarPTD',
    customPadding: '0',
    campos: [
      {
        etiqueta: 'checkbox',
        claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
        nombre: 'DeAcuerdo',
        label_i18n: 'ptd.deacuerdo_concertado',
        placeholder_i18n: 'ptd.deacuerdo_concertado',
        requerido: true,
        tipo: 'text',
      },
      {
        etiqueta: 'select',
        claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
        nombre: 'EstadoAprobado',
        label_i18n: 'GLOBAL.estado_aprobado',
        placeholder_i18n: 'GLOBAL.estado_aprobado',
        requerido: true,
        tipo: 'text',
      },
      {
        etiqueta: 'textarea',
        claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
        nombre: 'Observaciones',
        label_i18n: 'GLOBAL.observaciones',
        placeholder_i18n: 'GLOBAL.placeholder_observacion',
        requerido: true,
        tipo: 'text',
      },
      {
        etiqueta: 'input',
        claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
        nombre: 'QuienResponde',
        label_i18n: 'ptd.quien_responde',
        placeholder_i18n: 'ptd.placeholder_quien_responde',
        requerido: true,
        tipo: 'text',
      },
      {
        etiqueta: 'input',
        claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
        nombre: 'Rol',
        label_i18n: 'GLOBAL.rol',
        placeholder_i18n: 'GLOBAL.rol',
        requerido: true,
        tipo: 'text',
      },
    ],
  }
  