export let FORM_CONSOLIDADO = {
    titulo_i18n: 'ptd.formato_control_cumplimiento_norma',
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Guardar',
    modelo: 'Consolidado',
    customPadding: '0',
    campos: [
        {
            etiqueta: 'fileRev',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            clase: 'form-control',
            nombre: 'ArchivoSoporte',
            label_i18n: 'GLOBAL.adjuntar_documento',
            placeholder_i18n: 'GLOBAL.adjuntar_documento',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 5, // pendiente Id
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'QuienEnvia',
            label_i18n: 'ptd.quien_envia',
            placeholder_i18n: 'ptd.placeholder_quien_envia',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Rol',
            label_i18n: 'GLOBAL.rol',
            placeholder_i18n: 'GLOBAL.rol',
            requerido: true,
            tipo: 'text',
        }
    ],
}

export let FORM_RESPUESTA_DEC = {
    //titulo_i18n: 'ptd.formato_control_cumplimiento_norma',
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Guardar',
    modelo: 'RespuestaConsolidado',
    customPadding: '0',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Respuesta',
            label_i18n: 'ptd.respuesta',
            placeholder_i18n: 'ptd.respuesta',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'textarea',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Observaciones',
            label_i18n: 'GLOBAL.observaciones',
            placeholder_i18n: 'GLOBAL.placeholder_observacion',
            requerido: true,
            tipo: 'text',
        },
    ],
}

export let FORM_REVISION_CONSOLIDADO = {
    titulo_i18n: 'ptd.revision_consolidado',
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Guardar',
    modelo: 'RevisionConsolidado',
    customPadding: '0',
    campos: [
        {
            etiqueta: 'fileRev',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            clase: 'form-control',
            nombre: 'ArchivoSoporte',
            label_i18n: 'GLOBAL.adjuntar_documento',
            placeholder_i18n: 'GLOBAL.adjuntar_documento',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 5, // pendiente Id
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'textarea',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'Observaciones',
            label_i18n: 'GLOBAL.observaciones',
            placeholder_i18n: 'GLOBAL.placeholder_observacion',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'checkbox',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'CumpleNorma',
            label_i18n: 'ptd.ask_cumple_normatividad',
            placeholder_i18n: 'ptd.ask_cumple_normatividad',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'EnviarAprovacionDec',
            label_i18n: 'ptd.select_enviar_aprov_dec',
            placeholder_i18n: 'ptd.select_enviar_aprov_dec',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'QuienResponde',
            label_i18n: 'ptd.quien_responde',
            placeholder_i18n: 'ptd.placeholder_quien_responde',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Rol',
            label_i18n: 'GLOBAL.rol',
            placeholder_i18n: 'GLOBAL.rol',
            requerido: true,
            tipo: 'text',
        }
    ],
}