export let FORM_INFO_CARACTERISTICA = {
    // titulo: 'InfoCaracteristica',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'InfoCaracteristica',
    campos: [
        {
            etiqueta: 'select',
            relacion: false,
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'GrupoSanguineo',
            label_i18n: 'grupo_sanguineo',
            placeholder_i18n: 'grupo_sanguineo',
            requerido: true,
            tipo: 'text',
            opciones: [],
            key: 'Nombre',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Rh',
            relacion: false,
            label_i18n: 'rh',
            placeholder_i18n: 'rh',
            requerido: true,
            tipo: 'text',
            opciones: [],
            key: 'Nombre',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'GrupoEtnico',
            label_i18n: 'grupo_etnico',
            placeholder_i18n: 'grupo_etnico',
            requerido: true,
            tipo: 'GrupoEtnico',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'PaisNacimiento',
            label_i18n: 'pais_nacimiento',
            placeholder_i18n: 'pais_nacimiento',
            requerido: false, //Temporalmente mientras el servicio funciona
            tipo: 'Lugar',
            key: 'Nombre',
            opciones: [],
            entrelazado: true,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'DepartamentoNacimiento',
            label_i18n: 'departamento_nacimiento',
            placeholder_i18n: 'departamento_nacimiento',
            requerido: true,
            tipo: 'Lugar',
            key: 'Nombre',
            opciones: [],
            entrelazado: true,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Lugar',
            label_i18n: 'ciudad_nacimiento',
            placeholder_i18n: 'ciudad_nacimiento',
            requerido: true,
            tipo: 'Lugar',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'selectmultiple',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'TipoDiscapacidad',
            label_i18n: 'tipo_discapacidad',
            placeholder_i18n: 'tipo_discapacidad',
            requerido: true,
            tipo: 'TipoDiscapacidad',
            key: 'Nombre',
            opciones: [],
            entrelazado: true,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            clase: 'form-control',
            nombre: 'ComprobanteDiscapacidad',
            label_i18n: 'comprobante_discapacidad',
            placeholder_i18n: 'comprobante_discapacidad',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 8,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
            ocultar:true
          },
    ],
}
