import { Validators } from '@angular/forms';

export let FORM_ESPACIO_ACADEMICO = {
    campos_p1: [
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'nivel',
            label_i18n: 'GLOBAL.nivel',
            placeholder_i18n: 'GLOBAL.placeholder_nivel',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
            opciones: [],
            entrelazado: true, 
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'subnivel',
            label_i18n: 'GLOBAL.subnivel',
            placeholder_i18n: 'GLOBAL.placeholder_subnivel',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
            opciones: [],
            entrelazado: true,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'proyectoCurricular',
            label_i18n: 'GLOBAL.proyecto_academico',
            placeholder_i18n: 'GLOBAL.placeholder_proyecto_curricular',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
            opciones: [],
        },
    ],
    campos_p2: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'nombre',
            label_i18n: 'GLOBAL.nombre',
            placeholder_i18n: 'espacios_academicos.placeholder_nombre',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'codigo',
            label_i18n: 'GLOBAL.codigo',
            placeholder_i18n: 'espacios_academicos.placeholder_codigo',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'codigo_abreviacion',
            label_i18n: 'GLOBAL.codigo_abreviacion',
            placeholder_i18n: 'espacios_academicos.placeholder_codigo',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'plan_estudios',
            label_i18n: 'espacios_academicos.plan_estudios',
            placeholder_i18n: 'espacios_academicos.placeholder_plan_estudios',
            requerido: true,
            min: 0,
            validacion: [Validators.required, Validators.min(0)],
            tipo: 'number',
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'tipo',
            label_i18n: 'GLOBAL.tipo',
            placeholder_i18n: 'GLOBAL.placeholder_tipo',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'clase',
            label_i18n: 'GLOBAL.clase',
            placeholder_i18n: 'espacios_academicos.placeholder_tipo',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'enfoque',
            label_i18n: 'GLOBAL.enfoque',
            placeholder_i18n: 'espacios_academicos.placeholder_enfoque',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
            opciones: [],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
            nombre: 'creditos',
            label_i18n: 'GLOBAL.creditos',
            placeholder_i18n: 'espacios_academicos.placeholder_creditos',
            requerido: true,
            min: 1,
            validacion: [Validators.required, Validators.min(1)],
            tipo: 'number',
        },
        {
            etiqueta: 'input-table',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12 kindaTable',
            nombre: 'htd',
            label_i18n: 'espacios_academicos.htd',
            placeholder_i18n: 'espacios_academicos.placeholder_htd',
            requerido: true,
            min: 0,
            validacion: [Validators.required, Validators.min(0)],
            tipo: 'number',
            entrelazado: true,
        },
        {
            etiqueta: 'input-table',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12 kindaTable',
            nombre: 'htc',
            label_i18n: 'espacios_academicos.htc',
            placeholder_i18n: 'espacios_academicos.placeholder_htc',
            requerido: true,
            min: 0,
            validacion: [Validators.required, Validators.min(0)],
            tipo: 'number',
            entrelazado: true,
        },
        {
            etiqueta: 'input-table',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12 kindaTable',
            nombre: 'hta',
            label_i18n: 'espacios_academicos.hta',
            placeholder_i18n: 'espacios_academicos.placeholder_hta',
            requerido: true,
            min: 0,
            validacion: [Validators.required, Validators.min(0)],
            tipo: 'number',
            entrelazado: true,
        },
        {
            etiqueta: 'input-table',
            claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12 kindaTable',
            nombre: 'total',
            label_i18n: 'GLOBAL.total',
            placeholder_i18n: 'GLOBAL.total',
            requerido: false,
            min: 0,
            validacion: [Validators.min(0)],
            sololectura: true,
            tipo: 'number',
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'grupos',
            label_i18n: 'GLOBAL.grupos',
            placeholder_i18n: 'espacios_academicos.placeholder_grupos',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'text',
        },
        {
            etiqueta: 'selectMultiple',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'espacios_requeridos',
            label_i18n: 'espacios_academicos.espacios_requeridos',
            placeholder_i18n: 'espacios_academicos.placeholder_espacios_requeridos',
            requerido: false,
            validacion: [],
            tipo: 'text',
            entrelazado: true,
            opciones: [],
        },
    ],
    campos_p3: [
        {
            etiqueta: 'file',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'soporte',
            label_i18n: 'GLOBAL.soporte_documental',
            placeholder_i18n: 'GLOBAL.placeholder_soporte_documental',
            requerido: true,
            validacion: [Validators.required],
            tipo: 'file',
            formatos: 'pdf',
            tamanoMaximo: 2,
            entrelazado: true,
            archivos: [],
            archivosEnLinea: [],
            archivosEnLineaSuprimidos: [],
            validacionArchivos: {ErrTipo: false, ErrTam: false},
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'aprobado',
            label_i18n: 'espacios_academicos.aprobar_espacio',
            placeholder_i18n: 'espacios_academicos.placeholder_aprobar_espacio',
            requerido: false,
            validacion: [],
            tipo: 'text',
            ocultar: true,
            opciones: [],
        },
        {
            etiqueta: 'textarea',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            nombre: 'observaciones',
            label_i18n: 'GLOBAL.observacion',
            placeholder_i18n: 'GLOBAL.placeholder_observacion',
            requerido: false,
            validacion: [],
            sololectura: true,
            tipo: 'text',
        },
    ]
}