export const FORM_TRANSFERENCIA_INTERNA = {
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Guardar',
    modelo: 'InfoPersona',
    campos: [
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'PeriodoPreinscripcion',
            label_i18n: 'periodo_preinscripcion',
            placeholder_i18n: 'periodo_preinscripcion',
            requerido: true,
            tipo: 'PeriodoPreinscripcion',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'CalendarioAcademico',
            label_i18n: 'calendario_academico',
            placeholder_i18n: 'calendario_academico',
            requerido: true,
            tipo: 'CalendarioAcademico',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'ProyectoCurricular',
            label_i18n: 'proyecto_curricular',
            placeholder_i18n: 'proyecto_curricular',
            requerido: true,
            tipo: 'ProyectoCurricular',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'TipoInscripcion',
            label_i18n: 'tipo_inscripcion',
            placeholder_i18n: 'tipo_inscripcion',
            requerido: true,
            tipo: 'TipoInscripcion',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'CodigoEstudiante',
            label_i18n: 'codigo_estudiante',
            placeholder_i18n: 'codigo_estudiante',
            requerido: true,
            tipo: 'CodigoEstudiante',
            key: 'Nombre',
            opciones: [],
        },
    ]
}

export const FORM_SOLICITUD_TRANSFERENCIA = {
    tipo_formulario: 'mini',
    alertas: true,
    titulo:"Información de solicitud",
    btn: 'Guardar',
    modelo: 'InfoPersona',
    campos: [
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'ProgramaOrigen',
            label_i18n: 'programa_origen',
            placeholder_i18n: 'programa_origen',
            requerido: true,
            tipo: 'ProgramaOrigen',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'CantidadCreditos',
            label_i18n: 'cantidad_creditos_aprobados',
            placeholder_i18n: 'cantidad_creditos_aprobados',
            requerido: true,
            tipo: 'number',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'ProgramaDestino',
            label_i18n: 'programa_destino',
            placeholder_i18n: 'programa_destino',
            requerido: true,
            tipo: 'ProgramaDestino',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'textarea',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'MotivoCambio',
            label_i18n: 'motivo_cambio',
            placeholder_i18n: 'motivo_cambio',
            requerido: true,
            tipo: 'MotivoCambio',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-12',
            clase: 'form-control',
            nombre: 'SoporteDocumento',
            label_i18n: 'soportes_documentos',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
    ]
}