export const RESPUESTA_SOLICITUD = {
    titulo: 'solicitud_respuesta',
    tipo_formulario: 'mini',
    modelo: 'solicitudRespuesta',
    btn: 'Enviar respuesta',
    campos: [
        {
            etiqueta: 'textarea',
            tipo: 'textarea',
            nombre: 'Observacion',
            claseGrid: 'col-lg-8 col-md-6 col-sm-12 col-xs-12',
            label_i18n: 'observacion',
            requerido: false,
            key: 'Valor',
        },
        {
          etiqueta: 'select',
          claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
          nombre: 'RespuestaSolicitud',
          label_i18n: 'doc_valido',
          placeholder: '--Seleccionar--',
          requerido: true,
          tipo: 'select',
          key: 'Estado',
          opciones: [
            { Id: 9, valor: 'aprobado'},
            { Id: 11, valor: 'rechazado'},
            { Id: 14, valor: 'aplazado'},
          ],
          valor: ['prueva'],
        },
        // {
        //     etiqueta: 'checkbox',
        //     tipo: 'checkbox',
        //     nombre: 'DocValido',
        //     claseGrid: 'col-lg-4 col-md-6 col-sm-12 col-xs-12',
        //     label_i18n: 'doc_valido',
        //     requerido: false,
        //     key: 'Valor',
        // },
    ],
}
