export let FORM_INFO_CARACTERISTICA_PREGRADO = {
    // titulo: 'InfoCaracteristica',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'InfoCaracteristica',
    campos: [
        {
            etiqueta: 'select',
            relacion: false,
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'GrupoSanguineo',
            label_i18n: 'grupo_sanguineo',
            placeholder_i18n: 'grupo_sanguineo',
            requerido: true,
            tipo: 'text',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Rh',
            relacion: false,
            label_i18n: 'rh',
            placeholder_i18n: 'rh',
            requerido: true,
            tipo: 'text',
            opciones: [],
            key: 'Nombre',
        },
        {
            etiqueta: 'selectmultiple',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'TipoPoblacion',
            label_i18n: 'tipo_poclacion',
            placeholder_i18n: 'tipo_poclacion',
            requerido: true,
            tipo: 'TipoPoblacion',
            key: 'Nombre',
            opciones: [],
            entrelazado: true,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'PaisNacimiento',
            label_i18n: 'pais_nacimiento',
            placeholder_i18n: 'pais_nacimiento',
            requerido: true,
            tipo: 'Lugar',
            key: 'Nombre',
            opciones: [],
            entrelazado: true,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'DepartamentoNacimiento',
            label_i18n: 'departamento_nacimiento',
            placeholder_i18n: 'departamento_nacimiento',
            requerido: true,
            tipo: 'Lugar',
            key: 'Nombre',
            opciones: [],
            entrelazado: true,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Lugar',
            label_i18n: 'ciudad_nacimiento',
            placeholder_i18n: 'ciudad_nacimiento',
            requerido: true,
            tipo: 'Lugar',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'selectmultiple',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'TipoDiscapacidad',
            label_i18n: 'tipo_discapacidad',
            placeholder_i18n: 'tipo_discapacidad',
            requerido: true,
            tipo: 'TipoDiscapacidad',
            key: 'Nombre',
            opciones: [],
            entrelazado: true,
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'EPS',
            label_i18n: 'eps',
            placeholder_i18n: 'eps',
            requerido: true,
            tipo: 'EPS',
            key: 'NombreCompleto',
            opciones: [],
        },
        {
            etiqueta: 'mat-date',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'FechaVinculacionEPS',
            label_i18n: 'fecha_vinculacion',
            placeholder_i18n: 'fecha_vinculacion',
            requerido: true,
            tipo: 'date',
        },
        {
            etiqueta: 'input',
            relacion: false,
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'NumeroHermanos',
            label_i18n: 'hermanos',
            placeholder_i18n: 'hermanos',
            requerido: true,
            tipo: 'number',
            minimo: 0,
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
            nombre: 'GrupoSisben',
            label_i18n: 'puntaje',
            placeholder_i18n: 'puntaje',
            requerido: true,
            tipo: 'string',
            minimo: 0,

        },
        {
            etiqueta: 'file',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            clase: 'form-control',
            nombre: 'ComprobantePoblacion',
            label_i18n: 'comprobante_poblacion',
            placeholder_i18n: 'comprobante_poblacion',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 64,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
            ocultar: true,
        },
        {
            etiqueta: 'label',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            label_i18n: "placeholder_observacion",
            tipo: 'text',
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
            clase: 'form-control',
            nombre: 'ComprobanteDiscapacidad',
            label_i18n: 'comprobante_discapacidad',
            placeholder_i18n: 'comprobante_discapacidad',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 64,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
            ocultar: true,
        },
    ],
}
