
export let FORM_CALENDARIOEVENTO = {
    titulo: 'Calendarioevento',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Calendarioevento',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Descripcion',
        label_i18n: 'descripcion',
        placeholder_i18n: 'descripcion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Fechainicio',
        label_i18n: 'fechainicio',
        placeholder_i18n: 'fechainicio',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Fechafin',
        label_i18n: 'fechafin',
        placeholder_i18n: 'fechafin',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Periodoid',
        label_i18n: 'periodoid',
        placeholder_i18n: 'periodoid',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Tipoevento',
        label_i18n: 'tipoevento',
        placeholder_i18n: 'tipoevento',
        requerido: true,
        tipo: 'Tipoevento',
        // key: 'Name',
        opciones: [],
    },
    ],
}
