export const DATOS_SOLICITANTE = {
    titulo: 'solicitante',
    tipo_formulario: 'mini',
    modelo: 'Solicitante',
    campos: [
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Nombre',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'nombre',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Codigo',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'codigo',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Carrera',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'carrera',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Telefono',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'telefono',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'CorreoInstitucional',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'correo_inst',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'CorreoPersonal',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'correo_personal',
            deshabilitar: true,
        },
    ]
}