export let FORM_PROPUESTA_GRADO = {
  // titulo: 'PropuestaGrado',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  alertas: true,
  modelo: 'PropuestaGrado',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Nombre',
      label_i18n: 'titulo_proyecto',
      placeholder_i18n: 'placeholder_titulo_proyecto',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'GrupoInvestigacion',
      label_i18n: 'grupo_investigacion',
      placeholder_i18n: 'placeholder_grupo_investigacion',
      requerido: true,
      tipo: 'GrupoInvestigacion',
      key: 'name',
      opciones: [],
      // entrelazado: true,
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'LineaInvestigacion',
      label_i18n: 'linea_investigacion',
      placeholder_i18n: 'placeholder_linea_investigacion',
      requerido: true,
      tipo: 'LineaInvestigacion',
      key: 'st_name',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoProyectoId',
      label_i18n: 'tipo_proyecto',
      placeholder_i18n: 'tipo_proyecto',
      requerido: true,
      tipo: 'TipoProyecto',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'textarea',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'Resumen',
      label_i18n: 'resumen',
      placeholder_i18n: 'resumen',
      requerido: false,
      tipo: 'text',
    },
    {
      etiqueta: 'fileRev',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      clase: 'form-control',
      nombre: 'FormatoProyecto',
      label_i18n: 'formato_proyecto',
      placeholder_i18n: 'formato_proyecto',
      requerido: true,
      tipo: 'pdf',
      tipoDocumento: 5,
      formatos: 'pdf',
      url: '',
      tamanoMaximo: 5,
    }
  ],
}
