FROM node:10.15.3-alpine
#npm install -g npm
RUN npm install -g @angular/cli 
## rxjs-tslint tslint typescript
## RUN cd /usr/local/lib/node_modules/rxjs-tslint && npm install
USER $USER
WORKDIR /app
#correr dentro del shell del contenedor:
# rxjs-5-to-6-migrate -p src/tsconfig.app.json
# during the update
#npm uninstall --save-dev angular-cli
#npm install --save-dev @angular/cli@latest
#npm install --save @angular/animations@latest
# npm install --save @angular/common@latest
# npm install --save @angular/core@latest
#@angular/compiler@latest
#@angular/forms@latest
#@angular/platform-browser@latest @angular/platform-browser-dynamic@latest
# --save-dev typescript@3.1.1
# --save-dev @angular/compiler-cli@latest
# rxjs@latest @nebular/auth
#ng update @angular/cli && ng update @angular/core
#ng update @angular/material
#Actualizar dependencias faltantes:
#npm install --save @nebular/auth@latest @nebular/security@latest @nebular/theme@latest
#npm install --save @ng-bootstrap/ng-bootstrap@latest
#npm install --save nebular-icons@latest @ngrx/store@latest @swimlane/ngx-charts@latest @nebular/bootstrap@latest
#npm install --save angular2-toaster@latest jquery@latest popper.js@1.14.7 ng2-completer@latest ng2-ckeditor@latest ng2-smart-table@latest ng2-smart-table@latest
#npm install --save ngx-echarts@latest
#npm install --save @ngx-translate/core@latest  @ngx-translate/http-loader@latest
#npm install --save-dev codelyzer@latest tslint-language-service@latest
#Remover dependencias no necesarias:
#npm uninstall --save ngx-qrcode2