export let FORM_EXTERNO = {
  // titulo: 'FormacionAcademica',
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  btnLimpiar: 'Limpiar',
  modelo: 'InfoTransferenciaExterna',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'UniversidadViene',
      label_i18n: 'universidad_viene',
      placeholder_i18n: 'universidad_viene',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'CarreraViene',
      label_i18n: 'carrera_viene',
      placeholder_i18n: 'carrera_viene',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'UltimoSemestre',
      label_i18n: 'ultimo_semestre',
      placeholder_i18n: 'ultimo_semestre',
      requerido: true,
      tipo: 'number',
    },
    {
      etiqueta: 'textarea',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'Observaciones',
      label_i18n: 'observacion_trans',
      placeholder_i18n: 'observacion_trans',
      requerido: true,
      tipo: 'text',
    },
  ],
}
