export let FORM_IDIOMAS = {
  // titulo: 'Idiomas',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  btnLimpiar: 'Limpiar',
  alertas: true,
  modelo: 'InfoIdioma',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'IdiomaId',
      label_i18n: 'idioma',
      placeholder_i18n: 'idioma',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Nativo',
      label_i18n: 'idioma_nativo_pregunta',
      placeholder_i18n: 'nativo',
      valor: false,
      tipo: 'checkbox',
    },
    {
      etiqueta: 'checkbox',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'SeleccionExamen',
      label_i18n: 'idioma_examen_pregunta',
      placeholder_i18n: 'idioma_examen',
      valor: false,
      tipo: 'checkbox',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelEscribeId',
      label_i18n: 'nivel_escribe',
      placeholder_i18n: 'nivel_escribe',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelEscuchaId',
      label_i18n: 'nivel_escucha',
      placeholder_i18n: 'nivel_escucha',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelHablaId',
      label_i18n: 'nivel_habla',
      placeholder_i18n: 'nivel_habla',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelLeeId',
      label_i18n: 'nivel_lee',
      placeholder_i18n: 'nivel_lee',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelId',
      label_i18n: 'clasificacion_nivel_idioma',
      placeholder_i18n: 'clasificacion_nivel_idioma',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
  ],
}
