import { environment } from "../../../../environments/environment"

export let FORM_EXPERIENCIA_LABORAL = {
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  btnLimpiar: 'Limpiar',
  modelo: 'InfoExperienciaLaboral',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-10 col-md-10 col-sm-9 col-xs-8',
      nombre: 'Nit',
      label_i18n: 'nit',
      placeholder_i18n: 'nit',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'button',
      claseGrid: 'col-lg-2 col-md-2 col-sm-3 col-xs-4',
      nombre: 'BusquedaBoton',
      claseBoton: 'btn btn-primary btn-sm',
      icono: 'fa fa-search',
      label_i18n: 'buscar',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'NombreEmpresa',
      label_i18n: 'nombre_empresa',
      placeholder_i18n: 'nombre_empresa',
      requerido: true,
      deshabilitar: true,
      tipo: 'InfoPersona',
      key: 'NombreCompleto',
      opciones: [],
      entrelazado: true,
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-4 col-md-4 col-sm-12 col-xs-12',
      nombre: 'TipoOrganizacion',
      label_i18n: 'tipo_organizacion',
      placeholder_i18n: 'tipo_organizacion',
      requerido: true,
      deshabilitar: true,
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-4 col-md-4 col-sm-12 col-xs-12',
      nombre: 'Pais',
      label_i18n: 'pais_empresa',
      placeholder_i18n: 'pais_empresa',
      requerido: true,
      deshabilitar: true,
      tipo: 'Lugar',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-4 col-md-4 col-sm-12 col-xs-12',
      nombre: 'Direccion',
      label_i18n: 'direccion_empresa',
      placeholder_i18n: 'direccion_empresa',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Correo',
      label_i18n: 'correo_empresa',
      placeholder_i18n: 'correo_empresa',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Telefono',
      label_i18n: 'telefono_empresa',
      placeholder_i18n: 'telefono_empresa',
      requerido: true,
      deshabilitar: true,
      tipo: 'text',
    },
    {
      etiqueta: 'mat-date',
      claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
      nombre: 'FechaInicio',
      label_i18n: 'fecha_inicio',
      placeholder_i18n: 'fecha_inicio',
      requerido: true,
      tipo: 'date',
    },
    {
      etiqueta: 'mat-date',
      claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
      nombre: 'FechaFinalizacion',
      label_i18n: 'fecha_fin',
      placeholder_i18n: 'fecha_fin',
      requerido: true,
      tipo: 'date',
    },
    {
      etiqueta: 'button',
      claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
      nombre: 'ExperienciaBoton',
      claseBoton: 'btn btn-primary btn-sm',
      icono: '',
      label_i18n: 'experiencia_actual',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoDedicacion',
      label_i18n: 'tipo_dedicacion',
      placeholder_i18n: 'tipo_dedicacion',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoVinculacion',
      label_i18n: 'tipo_vinculacion',
      placeholder_i18n: 'tipo_vinculacion',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'autocomplete',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'Cargo',
      label_i18n: 'cargo',
      placeholder_i18n: 'cargo',
      placeholder_i18n_2: 'cargo_mensaje',
      path: environment.EXPERIENCIA_SERVICE,
      query: "cargo/?limit=0&query=Activo:true,Nombre__icontains:ROLE_TEXT_HERE&order=asc&sortby=Nombre&fields=Id,Nombre",
      keyToFilter: 'ROLE_TEXT_HERE',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'textarea',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'Actividades',
      label_i18n: 'descripcion_cargo',
      placeholder_i18n: 'descripcion_cargo',
      requerido: true,
      tipo: 'text',
      cantidadCaracteres: 400,
    },
    {
      etiqueta: 'fileRev',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      clase: 'form-control',
      nombre: 'Soporte',
      label_i18n: 'soporte_documento',
      placeholder_i18n: 'soporte_documento',
      requerido: true,
      tipo: 'pdf',
      tipoDocumento: 4,
      formatos: 'pdf',
      url: '',
      tamanoMaximo: 2,
    },
  ],
}
