export let FORM_ICFES_EXTERNO = {
  // titulo: 'FormacionAcademica',
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  btnLimpiar: 'Limpiar',
  modelo: 'InfoFormacionAcademica',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-5 col-sm-12 col-xs-12',
      nombre: 'TipoIcfes',
      label_i18n: 'tipo_icfes',
      placeholder_i18n: 'tipo_icfes',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-5 col-md-5 col-sm-10 col-xs-10',
      nombre: 'NúmeroRegistroIcfes',
      label_i18n: 'numero_registro',
      placeholder_i18n: 'numero_registro',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NúmeroRegistroIcfes',
      label_i18n: 'confirme_numero_registro',
      placeholder_i18n: 'confirme_numero_registro',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'LocalidadColegio',
      label_i18n: 'localidad_colegio',
      placeholder_i18n: 'localidad_colegio',
      requerido: true,
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoColegio',
      label_i18n: 'tipo_colegio',
      placeholder_i18n: 'tipo_colegio',
      requerido: true,
    },
    {
      etiqueta: 'textarea',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'Observaciones_icfes',
      label_i18n: 'observacion',
      placeholder_i18n: 'observacion',
      requerido: true,
      tipo: 'text',
    },
  ],
}
