export let FORM_CRITERIO_ICFES = {
    // titulo: 'InfoPersona',
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Guardar',
    modelo: 'InfoCriterioIcfes',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-12 col-md-6 col-sm-12 col-xs-12',
            nombre: 'PorcentajeTotal',
            label_i18n: 'porcentaje_total',
            placeholder_i18n: 'porcentaje_total',
            requerido: true,
            tipo: 'number',
            minimo: 0,
            maximolog: 100,
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Area1',
            label_i18n: 'area_1',
            placeholder_i18n: 'area_1',
            requerido: true,
            tipo: 'number',
            minimo: 0,
            maximolog: 100,
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Area2',
            label_i18n: 'area_2',
            placeholder_i18n: 'area_2',
            requerido: true,
            tipo: 'number',
            minimo: 0,
            maximolog: 100,
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Area3',
            label_i18n: 'area_3',
            placeholder_i18n: 'area_3',
            requerido: true,
            tipo: 'number',
            minimo: 0,
            maximolog: 100,
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Area4',
            label_i18n: 'area_4',
            placeholder_i18n: 'area_4',
            requerido: true,
            tipo: 'number',
            minimo: 0,
            maximolog: 100,
        },
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            nombre: 'Area5',
            label_i18n: 'area_5',
            placeholder_i18n: 'area_5',
            requerido: true,
            tipo: 'number',
            minimo: 0,
            maximolog: 100,
        },

    ],
}
