export let FORM_COMPROBANTE = {
  titulo: 'PagoComprobante',
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  modelo: 'PagoComprobante',
  campos: [
    {
      etiqueta: 'mat-date',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'FechaPago',
      label_i18n: 'fecha_pago',
      placeholder_i18n: 'fecha_pago',
      requerido: false,
      tipo: 'date',
      deshabilitar: true,
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'EstadoPagoRecibo',
      label_i18n: 'estado_pago',
      placeholder_i18n: 'estado_pago',
      requerido: false,
      tipo: 'text',
      deshabilitar: true,
    },
    {
      etiqueta: 'file',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      clase: 'form-control',
      nombre: 'Comprobante',
      label_i18n: 'comprobante',
      placeholder_i18n: 'comprobante',
      requerido: true,
      tipo: 'pdf',
      tipoDocumento: 8,
      formatos: 'pdf',
      url: '',
      tamanoMaximo: 2,
    },
  ],
}
