export const FORM_TRANSFERENCIA_INTERNA = {
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Guardar',
    modelo: 'InfoPersona',
    campos: [
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'PeriodoPreinscripcion',
            label_i18n: 'periodo_preinscripcion',
            placeholder_i18n: 'periodo_preinscripcion',
            requerido: true,
            tipo: 'PeriodoPreinscripcion',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'CalendarioAcademico',
            label_i18n: 'calendario_academico',
            placeholder_i18n: 'calendario_academico',
            requerido: true,
            tipo: 'CalendarioAcademico',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'ProyectoCurricular',
            label_i18n: 'proyecto_curricular',
            placeholder_i18n: 'proyecto_curricular',
            requerido: true,
            tipo: 'ProyectoCurricular',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'TipoInscripcion',
            label_i18n: 'tipo_inscripcion',
            placeholder_i18n: 'tipo_inscripcion',
            requerido: true,
            tipo: 'TipoInscripcion',
            key: 'Nombre',
            opciones: [],
        },
        {
            etiqueta: 'select',
            claseGrid: 'col-sm-12 col-xs-12',
            nombre: 'CodigoEstudiante',
            label_i18n: 'codigo_estudiante',
            placeholder_i18n: 'codigo_estudiante',
            requerido: true,
            tipo: 'CodigoEstudiante',
            key: 'Nombre',
            opciones: [],
        },
    ]
}