export const FORM_SOLICITUD_PRACTICAS = {
    tipo_formulario: 'mini',
    alertas: true,
    btn: 'Enviar',
    modelo: 'InfoPracticasAcademicas',
    campos: [
        {
            etiqueta: 'select',
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'Periodo',
            label_i18n: 'periodo',
            requerido: true,
            opciones: [],
            key: 'Nombre'
        },
        {
            etiqueta: 'select',
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'Proyecto',
            label_i18n: 'proyecto',
            requerido: true,
            opciones: [],
            key: 'Nombre'
        },
        {
            etiqueta: 'select',
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'EspacioAcademico',
            label_i18n: 'espacio_academico',
            requerido: true,
            opciones: [],
            key: 'Nombre'
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Semestre',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'semestre',
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'NumeroEstudiantes',
            claseGrid: "col-12 col-md-6",
            label_i18n: 'numero_estudiantes',
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'NumeroGrupos',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'num_grupos',
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'datetime-local',
            nombre: 'FechaHoraSalida',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'fecha_salida',
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'datetime-local',
            nombre: 'FechaHoraRegreso',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'fecha_regreso',
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Duracion',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'duracion',
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'NumeroVehiculos',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'numero_vehiculos',
            requerido: true,
        },
        {
            etiqueta: 'select',
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'TipoVehiculo',
            label_i18n: 'tipo_vehiculo',
            requerido: true,
            opciones: [],
            key: 'Nombre'
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'Cronograma',
            label_i18n: 'cronograma_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'Presupuesto',
            label_i18n: 'presupuesto_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'Presentacion',
            label_i18n: 'presentacion_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'ListaEstudiantes',
            label_i18n: 'lista_estudiantes',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
    ]
}