export const FORM_SOLICITUD_PRACTICAS = {
    tipo_formulario: 'mini',
    alertas: true,
    nombre: "SOLICITUD_PRACTICAS",
    btn: 'Siguiente',
    modelo: 'InfoPracticasAcademicas',
    campos: [
        {
            etiqueta: 'select',
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'Periodo',
            label_i18n: 'periodo',
            requerido: true,
            opciones: [],
            key: 'Nombre',
            deshabilitar: true,
        },
        {
            etiqueta: 'select',
            entrelazado: true,
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'Proyecto',
            label_i18n: 'proyecto',
            requerido: true,
            opciones: [],
            key: 'Nombre',
            deshabilitar: false,
        },
        {
            etiqueta: 'select',
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'EspacioAcademico',
            label_i18n: 'espacio_academico',
            requerido: true,
            opciones: [],
            key: 'Nombre',
            deshabilitar: false,
        },
        {
            etiqueta: 'input',
            tipo: 'number',
            nombre: 'Semestre',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'semestre',
            requerido: true,
            minimo: 0,
            deshabilitar: false,
        },
        {
            etiqueta: 'input',
            tipo: 'number',
            nombre: 'NumeroEstudiantes',
            claseGrid: "col-12 col-md-6",
            label_i18n: 'numero_estudiantes',
            requerido: true,
            minimo: 0,
            deshabilitar: false,
        },
        {
            etiqueta: 'input',
            tipo: 'number',
            nombre: 'NumeroGrupos',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'num_grupos',
            requerido: true,
            minimo: 0,
            deshabilitar: false,
        },
        {
            etiqueta: 'input',
            tipo: 'datetime-local',
            nombre: 'FechaHoraSalida',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'fecha_salida',
            requerido: true,
            deshabilitar: false,
        },
        {
            etiqueta: 'input',
            tipo: 'datetime-local',
            nombre: 'FechaHoraRegreso',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'fecha_regreso',
            requerido: true,
            deshabilitar: false,
        },
        {
            etiqueta: 'input',
            tipo: 'number',
            nombre: 'Duracion',
            claseGrid: 'col-12 col-sm-6 col-md-4',
            label_i18n: 'duracion',
            requerido: true,
            minimo: 0,
            deshabilitar: false,
        },
        {
            etiqueta: 'input',
            tipo: 'number',
            nombre: 'NumeroVehiculos',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'numero_vehiculos',
            requerido: true,
            minimo: 0,
            deshabilitar: false,
        },
        {
            etiqueta: 'select',
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'TipoVehiculo',
            label_i18n: 'tipo_vehiculo',
            requerido: true,
            opciones: [],
            key: 'Nombre',
            deshabilitar: false,
        },
    ]
}


export const FORM_SOPORTES_DOCUMENTALES = {
    tipo_formulario: 'mini',
    alertas: true,
    nombre: "SOPORTES_DOCUMENTALES",
    btn: 'Enviar',
    modelo: 'documental',
    campos: [
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'Cronograma',
            label_i18n: 'cronograma_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 47,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'Presupuesto',
            label_i18n: 'presupuesto_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 48,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'Presentacion',
            label_i18n: 'presentacion_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 49,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'ListaEstudiantes',
            label_i18n: 'lista_estudiantes',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 50,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'GuiaPractica',
            label_i18n: 'guia_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 51,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'ListaPersonalApoyo',
            label_i18n: 'lista_personal_apoyo',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 52,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'ActaCompromiso',
            label_i18n: 'acta_compromiso',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'InformacionAsistente',
            label_i18n: 'info_asistencia_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        }
    ]
}


export const FORM_DOCUMENTOS_ADICIONALES = {
    tipo_formulario: 'mini',
    alertas: true,
    nombre: "DOCUMENTOS_ADICIONALES",
    btn: 'Enviar',
    modelo: 'documental',
    campos: [
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'ActaCompromiso',
            label_i18n: 'acta_compromiso',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-6 mb-5',
            clase: 'form-control',
            nombre: 'InformacionAsistente',
            label_i18n: 'info_asistencia_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        }
    ]
}


export const FORM_DOCUMENTOS_ADICIONALES_LEGALIZACION = {
    tipo_formulario: 'mini',
    alertas: true,
    nombre: "Documentos adicionales",
    btn: 'Enviar',
    modelo: 'documental',
    campos: [
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-12',
            clase: 'form-control',
            nombre: 'InformePractica',
            label_i18n: 'informe_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-12 col-md-12',
            clase: 'form-control',
            nombre: 'CumplidoPractica',
            label_i18n: 'cumplido_practica',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        }
    ]
}

export const FORM_RESPUESTA_SOLICITUD = {
    tipo_formulario: 'mini',
    alertas: true,
    nombre: "RESPUESTA_SOLICITUD",
    btn: 'Dar respuesta',
    modelo: 'documental',
    campos: [
        {
            etiqueta: 'mat-date',
            tipo: 'datetime-local',
            nombre: 'FechaRespuesta',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'fecha_respuesta',
            requerido: true,
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Nombre',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'nombre_usuario',
            requerido: true,
            minimo: 0,
            deshabilitar: true,
        },
        {
            etiqueta: 'select',
            tipo: 'text',
            claseGrid: "col-12 col-md-6",
            nombre: 'Estado',
            label_i18n: 'estado',
            requerido: true,
            opciones: [],
            key: 'Nombre',
            deshabilitar: false,
        },
        {
            etiqueta: 'textarea',
            tipo: 'text',
            nombre: 'Comentario',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'comentario',
            requerido: true,
            minimo: 0,
            deshabilitar: false,
        },
    ]
}
