export const DOCENTE_PRACTICA = {
    titulo: 'docente',
    tipo_formulario: 'mini',
    modelo: 'DocentePractica',
    campos: [
        {
            etiqueta: 'input',
            claseGrid: 'col-lg-10 col-md-10 col-sm-9 col-xs-8',
            nombre: 'docDocente',
            label_i18n: 'docDocente',
            placeholder_i18n: 'docDocente',
            requerido: true,
            tipo: 'text',
        },
        {
            etiqueta: 'button',
            claseGrid: 'col-lg-2 col-md-2 col-sm-3 col-xs-4',
            nombre: 'BusquedaBoton',
            claseBoton: 'btn btn-primary btn-sm',
            icono: 'fa fa-search',
            label_i18n: 'buscar',
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Nombre',
            claseGrid: 'col-12 col-sm-6 col-md-3',
            label_i18n: 'nombre',
            placeholder_i18n: 'nombre',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Vinculacion',
            claseGrid: 'col-12 col-sm-6 col-md-3',
            label_i18n: 'vinculacion',
            placeholder_i18n: 'vinculacion',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Correo',
            claseGrid: 'col-12 col-sm-6 col-md-3',
            label_i18n: 'correo',
            placeholder_i18n: 'correo',
            deshabilitar: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'Telefono',
            claseGrid: 'col-12 col-sm-6 col-md-3',
            label_i18n: 'telefono',
            placeholder_i18n: 'telefono',
            deshabilitar: true,
        },
        {
            etiqueta: 'button',
            tipo: 'button',
            nombre: 'AgregarDocente',
            claseGrid: 'col-12 text-center',
            claseBoton: 'btn btn-success btn-sm',
            label_i18n: 'agregar_docente',
            resultado: true,
            requerido: true,
        },
    ]
}