export const ACTUALIZAR_NOMBRE = {
    titulo: 'solicitud_encabezado',
    tipo_formulario: 'mini',
    modelo: '',
    btn: 'Enviar',
    campos: [
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'FechaSolicitud',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'fecha',
            deshabilitar: true,
            requerido: true,
        },
        {
            etiqueta: 'div',
            claseGrid: 'offset-sm-6'
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            label_i18n: 'nombre_actual',
            nombre: 'NombreActual',
            claseGrid: 'col-12 col-sm-6',
            deshabilitar: true,
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'ApellidoActual',
            deshabilitar: true,
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'apellido_actual',
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'NombreNuevo',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'nombre_nuevo',
            requerido: true,
        },
        {
            etiqueta: 'input',
            tipo: 'text',
            nombre: 'ApellidoNuevo',
            claseGrid: 'col-12 col-sm-6',
            label_i18n: 'apellido_nuevo',
            requerido: true,
        },
        {
            etiqueta: 'file',
            claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
            clase: 'form-control',
            nombre: 'Documento',
            label_i18n: 'soporte_id',
            placeholder_i18n: 'soporte_documento',
            requerido: true,
            tipo: 'pdf',
            tipoDocumento: 25,
            formatos: 'pdf',
            url: '',
            tamanoMaximo: 2,
        },
    ]
}