
export let FORM_NOTIFICACION_ESTADO_USUARIO = {
    titulo: 'NotificacionEstadoUsuario',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'NotificacionEstadoUsuario',
    campos: [
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Notificacion',
        label_i18n: 'notificacion',
        placeholder_i18n: 'notificacion',
        requerido: true,
        tipo: 'Notificacion',
        key: 'CuerpoNotificacion',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'NotificacionEstado',
        label_i18n: 'notificacion_estado',
        placeholder_i18n: 'notificacion_estado',
        requerido: true,
        tipo: 'NotificacionEstado',
        key: 'Nombre',
        opciones: [],
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'Fecha',
        label_i18n: 'fecha',
        placeholder_i18n: 'fecha',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Usuario',
        label_i18n: 'usuario',
        placeholder_i18n: 'usuario',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Activo',
        label_i18n: 'activo',
        placeholder_i18n: 'activo',
        requerido: true,
        tipo: 'checkbox',
    },
    ],
}
