export let FORM_DOCUMENTO_PROGRAMA = {
  // titulo: 'DocumentoPrograma',
  tipo_formulario: 'mini',
  btn: 'Guardar',
  btnLimpiar: 'Limpiar',
  alertas: true,
  modelo: 'DocumentoPrograma',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'DocumentoProgramaId',
      label_i18n: 'tipo_documento_programa',
      placeholder_i18n: 'tipo_documento_programa',
      requerido: true,
      tipo: 'DocumentoPrograma',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'file',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      clase: 'form-control',
      nombre: 'Documento',
      label_i18n: 'soporte_documento',
      placeholder_i18n: 'soporte_documento',
      requerido: false,
      tipo: 'pdf',
      tipoDocumento: 6,
      formatos: 'pdf',
      url: '',
      tamanoMaximo: 2,
    },
  ],
}
